Args: --data_dir=/workspace/data --log_dir=$RUNDIR --training_iteration=1000
Cmd: main.py
EnvVars: []
ExecutionDir: /src/klchart_p2
Images:
  BaseImage: tensorflow/tensorflow:latest
  GpuImage: tensorflow/tensorflow:latest-gpu
  PSImage: tensorflow/tensorflow:latest
Jupyter:
  UseGPU: true
  Image: lsheiba/tensorflow:latest-gpu
MonitoringNamespace: kuberlab
Requests:
  CPU: 100m
  CPULimit: 8000m
  GPU: 1
  Memory: 2Gi
  MemoryLimit: 64Gi
  PsPods: 0
  WorkerPods: 0
Volumes:
- isLibDir: false
  isTrainLogDir: true
  mountPath: /training
  name: training
  clusterStorage: {{ .storage }}
  subPath: training
- gitRepo:
    repository: https://github.com/lsheiba/klchart_p3
  isLibDir: false
  isTrainLogDir: false
  mountPath: /src
  name: src
  subPath: ""
- isLibDir: true
  isTrainLogDir: false
  mountPath: /workspace/lib
  name: lib
  clusterStorage: {{ .storage }}
  subPath: lib
- isLibDir: false
  isTrainLogDir: false
  mountPath: /workspace/data
  name: data
  clusterStorage: {{ .storage }}
  subPath: /data
